//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System .Collections;
namespace TeacherManger
{
	public class TeacherManger
	{
		public Hashtable h =new Hashtable(); 

		public bool  AddTeacher(Teacher t)
		{
			bool b = FindTeacherByName(t.Name);
				if(b==false)
			{
				h.Add(t.Name,t);
				return true;
			}else
			{
				return false;
			}
		}
		public bool FindTeacherByName(string name)
		{
			bool b = false;
			foreach(Teacher t in h.Values)
			{
				if(t.Name ==name)
				{
					b = true;
					break;
				}
			}
			return b;
		}
		public bool DeletTeacherByName(string name)
		{
			bool b = false;
			foreach(Teacher t in h.Values)
			{
				if(h.ContainsKey(name))
				{
					h.Remove(name);
					b = true;
				}
			}
			return b;
	
		}
		public bool ChangeTeacherByName(string name)
		{
			bool b = false;
			foreach (Teacher t in h.Values )
			{
				if(h.ContainsKey(name))
				{
					Console.WriteLine (name+"增加后的工资为："+ (t.Salary +=500));
					b = true;
				}
			}
			return b;
		}
	}
}

